export default [
  'Fiction',
  'Non-fiction',
  'Mystery/Thriller',
  'Science Fiction',
  'Fantasy',
  'Historical Fiction',
  'Romance',
  'Horror',
  'Biography/Autobiography',
  'Self-help/Personal Development',
  'Business/Entrepreneurship',
  'Travel',
  'Science',
  'History',
  'Philosophy',
  'Religion/Spirituality',
  'Art/Photography',
  "Children's Books",
  'Young Adult',
  'Poetry',
  'Drama/Plays',
  'Cookbooks',
  'Comics/Graphic Novels',
  'Sports',
  'Health/Fitness',
  'Psychology',
  'Education',
  'Technology',
  'Environment/Ecology',
  'Parenting/Family'
];
